---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("rest_inspec")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec |> 
  filter(
    critical_flag == "Critical",
    grade %in% c("A", "B", "C"), boro != "Missing",
    str_detect(dba, "[Cc][Oo][Ff][Ff][Ee][Ee]")) |> 
  group_by(boro, violation_code, violation_description) |> 
  summarize(n = n(), .groups = "drop") |> 
  group_by(boro) |> 
  slice_max(n, n = 5) |> 
  mutate(text_label = str_c("Violation: ", violation_description)) |> 
  plot_ly(x = ~reorder(violation_code, n), y = ~n, type = "bar", color = ~boro, 
    text = ~text_label) |> 
  layout(
    xaxis = list(title = "Violation Code"),
    yaxis = list(title = "Count"),
    barmode = "stack")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec |> 
  filter(critical_flag == "Critical",
         grade %in% c("A", "B", "C"), boro != "Missing",
         grade_date >= as.Date("2015-01-01"), 
         grade_date <= as.Date("2015-12-31")) |> 
  count(boro, grade_date) |> 
  plot_ly(
    x = ~grade_date, y = ~n, type = "scatter", mode = "lines", color = ~boro)
```

### Chart C

```{r}
rest_inspec |> 
  filter(
    grade %in% c("A", "B", "C"), boro != "Missing",
    str_detect(dba, "[Cc][Oo][Ff][Ff][Ee][Ee]")) |> 
  group_by(boro, grade) |> 
  count(boro) |> 
  mutate(
    boro = str_to_title(boro),
    boro = fct_reorder(boro, n)) |> 
  plot_ly(
    x = ~boro, y = ~n, type = "bar", color = ~grade) |> 
  layout(barmode = "stack")
```

